--liquibase formatted sql

--changeset portfolio:dml-002-seed-feature-toggles
--comment: Seed default feature toggles for tiered access control
INSERT INTO feature_toggles (feature_key, is_enabled, allowed_tiers) VALUES
('PORTFOLIO_MANAGEMENT', TRUE, 'FREE,PRO,PREMIUM'),
('BASIC_SCREENER', TRUE, 'FREE,PRO,PREMIUM'),
('ADVANCED_SCREENER', TRUE, 'PRO,PREMIUM'),
('BASIC_RISK_METRICS', TRUE, 'FREE,PRO,PREMIUM'),
('ADVANCED_RISK_ANALYTICS', TRUE, 'PREMIUM'),
('VAR_CALCULATION', TRUE, 'PREMIUM'),
('MONTE_CARLO_SIMULATION', TRUE, 'PREMIUM'),
('STRESS_TESTING', TRUE, 'PREMIUM'),
('CORRELATION_MATRIX', TRUE, 'PRO,PREMIUM'),
('STRATEGY_ENGINE', TRUE, 'PRO,PREMIUM'),
('STRATEGY_BACKTESTING', TRUE, 'PREMIUM'),
('AUTOMATED_TRADING', TRUE, 'PREMIUM'),
('PAPER_TRADING', TRUE, 'PRO,PREMIUM'),
('REAL_TIME_DATA', TRUE, 'PREMIUM'),
('BATCH_DEEP_ANALYSIS', TRUE, 'PREMIUM'),
('CSV_EXPORT', TRUE, 'PRO,PREMIUM'),
('PDF_EXPORT', TRUE, 'PREMIUM'),
('EMAIL_ALERTS', TRUE, 'FREE,PRO,PREMIUM'),
('SMS_ALERTS', TRUE, 'PRO,PREMIUM'),
('PRICE_ALERTS', TRUE, 'PRO,PREMIUM'),
('CRYPTO_TRADING', TRUE, 'PRO,PREMIUM'),
('OPTIONS_GREEKS', TRUE, 'PRO,PREMIUM'),
('TAX_LOSS_HARVESTING', TRUE, 'PREMIUM'),
('ADMIN_PANEL', TRUE, 'PREMIUM');

--rollback DELETE FROM feature_toggles;
